### ISSUE TITLE
Migrate ical4j 3.x → 4.x

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/ical4android#106]
ical4j 4.0 will be released soon, and new development will then only be available in 4.x.

- [ ] Wait until ical4j 4.x is released and stable
- [ ] Create branch that uses ical4j 4.x
- [ ] Make sure that everything is working (including tests)

Update: Because this is such a large change, we should do it with extreme care (as it has the potential to break DAVx5 in many ways), extensive testing and when it's time for it.

**Comment by ArnyminerZ** [comment]
Some annotations regarding the migration (updating):
- Uses of `obj is DateTime` have been replaced with `until.isSupported(ChronoUnit.HOURS)`, which should work fine as an alternative. Maybe it's not a bad idea to use `DateUtils.isDateTime` or create a shortcut of something like `DateUtils.hasTime`. This is because the new version uses `Temporal` which may be an `Instant`, a `ZonedDateTime`, or a `LocalDate`, to give some examples. So we can't use types here.

**Comment by rfc2822** [comment]
Closing for when it's time :)
